[project]
name = "ai-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.38.13",
    "jsonpickle>=4.0.5",
    "mcp>=1.8.0",
    "rich>=14.0.0",
    "simple-term-menu>=1.6.6",
    "typer>=0.15.3",
]
